# Config file for Air
root = "."

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp"]
  delay = 1000 # ms

[log]
  color = "auto"
  time = true

[run]
  cmd = ""
  watch_dir = "."
  watch_ext = ["go"]
  include_dir = ["."]
  exclude_dir = ["vendor", "tmp"]